const userTableCreation = `
CREATE TABLE IF NOT EXISTS users (
id varchar(255) PRIMARY KEY UNIQUE,
username varchar(255),
email varchar(255) UNIQUE,
password varchar(255),
created_at TIMESTAMP
)
`;

const placeTableCreation = `
CREATE TABLE IF NOT EXISTS places (
id INT PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
user_id varchar(255),
title TEXT,
address TEXT,
photos TEXT[],
description TEXT,
perks TEXT[],
extraInfo TEXT,
checkIn varchar(255),
checkout varchar(255),
maxGuest varchar(255),
price varchar(255),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (user_id) REFERENCES users(id)
)
`;

const profileImageTableCreation = `
CREATE TABLE IF NOT EXISTS userprofileimage (
id INT PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
user_id varchar(255) UNIQUE,
image_id varchar(255),
FOREIGN KEY (user_id) REFERENCES users(id)
)
`;

module.exports = {
  userTableCreation,
  placeTableCreation,
  profileImageTableCreation,
};
